version: '3.1'

services:
  greenplum:
    image: datagrip/greenplum:5.17
    container_name: greenplum
    ports:
      - 5432:5432
      - 4444:4444
    restart: always
    networks:
      - wakening

networks:
  wakening:
    driver: bridge